Repository AakashSharma7269/erin, pull requests merged in 2021-07, with the labels that each got.

#5 add default reason for moderator actions, allow unmuting users with no mutes logged
  src/cogs/mod.py
Labels: Feature request

#12 Can run commands by pinging bot and add prefixes command
  src/cogs/config.py
  src/cogs/help.py
  src/main.py
Labels: Feature request, Important

#13 Changes to delpunishments command
  src/cogs/mod.py
Labels: P2 Bug

#11 Add image manipulation cog
  requirements.txt
  src/assets/daviegun.png
  src/assets/daviesad.png
  src/assets/impact.ttf
  src/assets/linus.jpg
  src/assets/nintendodirect.jpg
  src/assets/scott.png
  src/assets/times.ttf
  src/cogs/image.py
Labels: Feature request
